name: Activity Summary

on:
  schedule:
    - cron: '30 7 * * 0'
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r github-notify-ml/requirements.txt
        pip install -r requirements.txt
    - name: run script
      env:
        GH_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SMTP_HOST: localhost
        SMTP_USERNAME: foo
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_SSL: TRUE
      run: |
        python main.py send
